# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.user:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, controller: ~, manager_type: orm, group: admin, label: User }

    admin.particular:
        class: App\Admin\ParticularAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Particular, controller: ~, manager_type: orm, group: admin, label: Particular }

    admin.socio:
        class: App\Admin\SocioAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Socio, controller: ~, manager_type: orm, group: admin, label: Socio }

    admin.cuota:
        class: App\Admin\CuotaAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Cuota, controller: ~, manager_type: orm, group: admin, label: Cuota, default: true }

    admin.cuotapendiente:
        class: App\Admin\CuotaPendienteAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Cuota, controller: ~, manager_type: orm, group: admin, label: CuotaPendiente }

    admin.asignar_cuota:
        class: App\Admin\AsignarCuotaAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\AsignarCuota, controller: ~, manager_type: orm, group: admin, label: AsignarCuota }

    admin.categoria:
        class: App\Admin\CategoriaAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Categoria, controller: ~, manager_type: orm, group: admin, label: Categoria }

    admin.pago_cuota:
        class: App\Admin\PagoCuotaAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\PagoCuota, controller: ~, manager_type: orm, group: admin, label: PagoCuota }

    admin.pago_cuota_detalle:
        class: App\Admin\PagoCuotaDetalleAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\PagoCuotaDetalle, controller: ~, manager_type: orm, group: admin, label: PagoCuotaDetalle }
